const gulpConfig = {
    INFO: {
        /* Application name */
        TITLE: 'Angular 2 Quickstart',

        /* Keywords for meta tag */
        KEYWORDS: 'angular, angular2, ng2, quickstart',

        /* Description for meta tag */
        DESCRIPTION: 'Description...'
    },

    /* Defines whether to build application for production or development */
    PRODUCTION: false,
    FEATURES: {
        /* Whether to show custom 404 and 500 error pages or default pages generated by ExpressJS */
        CUSTOM_ERROR_PAGES: true
    },
    FOLDERS: {
        /* Target folder name for built distribution */
        DIST: 'dist',

        /* Folders for server and client source files */
        SOURCES: {
            CLIENT: 'src_client',
            SERVER: 'src_server'
        },
        CLIENT: {
            /* ExpressJS static folder - to deploy client app files */
            ROOT: 'public',

            /* Folders names inside root for vendor,styles and images */
            CONTENT: {
                APP: 'app',
                VENDOR: 'vendor',
                STYLES: 'resources/styles',
                IMAGES: 'resources/images'
            }
        },
        SERVER: {
            /* URL part name for application API */
            API_BASE_PATH: 'api',

            /* Folder name for HTTP Requests logs */
            REQUESTS_LOGS: '_logs_requests',

            /* Folder name for app activity logs */
            ACTIVITY_LOGS: '_logs_activity'
        }
    },
    PORT: {
        /* Server port when running in production enviroment */
        PRODUCTION: 80,

        /* Server port when running in devemopment mode */
        DEVELOPMENT: 8888
    },
    LOGS: {
        /* Enable or disable Morgan HTTP logs */
        REQUESTS_LOGS_ENABLED: true,

        /* Format of the Morgan logs
        *  Presets are: combined, common, dev, short and tiny
        * */
        REQUESTS_FORMAT: ':date[iso] :remote-user :status :method :url (:response-time ms)',

        /* Whether to include all requests all only errors */
        REQUESTS_ONLY_ERRORS: true,

        /* Enable or disable app activity logs */
        ACTIVITY_LOGS_ENABLED: true,

        /* Maximum size in MB per activity log file */
        ACTIVITY_MAX_SIZE_MB: 1,

        /* Maximum files to keep on server for activity logs */
        ACTIVITY_MAX_FILES: 10,

        /* Whether to write logs as json or plain text */
        ACTIVITY_JSON_FORMAT: false
    },
    UTILITIES: {
        /* Whether to include jQuery in bundleded vendor scripts */
        JQUERY: true,

        /* Whether to include Lodash in bundleded vendor scripts */
        LODASH: true,

        /* Whether to include MomentJS in bundleded vendor scripts */
        MOMENT: true,

        /* If MomentJS included, defines whether to include version with locales extensions */
        MOMENT_WITH_LOCALES: true
    }
};

module.exports = gulpConfig;